import { scryptSync, timingSafeEqual } from 'node:crypto';

/**
 * NODE RUNTIME ONLY. Never import this from middleware.ts or from lib/auth.ts —
 * the node:crypto specifier below would be pulled into the Edge bundle and
 * break the build. Route handlers and server actions are fine.
 */

/**
 * Constant-time check of a submitted password against ADMIN_PASSWORD_HASH,
 * stored as "salt:hash" (both hex) and generated by scripts/hash-password.mjs.
 */
export function verifyPassword(password: string): boolean {
  const stored = process.env.ADMIN_PASSWORD_HASH;
  if (!stored) return false;

  const [salt, hash] = stored.split(':');
  if (!salt || !hash) return false;

  let expected: Buffer;
  try {
    expected = Buffer.from(hash, 'hex');
  } catch {
    return false;
  }
  // Buffer.from ignores trailing junk rather than throwing, so check the length
  // survived the round trip before trusting it as a key length.
  if (expected.length === 0 || expected.length * 2 !== hash.length) return false;

  const actual = scryptSync(password, salt, expected.length);
  return timingSafeEqual(expected, actual);
}

export function isAdminPasswordConfigured(): boolean {
  return Boolean(process.env.ADMIN_PASSWORD_HASH);
}
