/**
 * Lead shapes and pipeline vocabulary. Pure types and constants only.
 *
 * Kept separate from lib/firestore.ts on purpose: LEAD_STATUSES is a *value*,
 * so a client component importing it from the storage module would pull
 * firebase-admin — and node:crypto with it — into the browser bundle. Anything
 * that runs outside Node imports from here.
 */

/**
 * Pipeline stages, in order. Exported so the admin UI can render the funnel
 * without redeclaring the list and drifting out of sync with what is stored.
 */
export const LEAD_STATUSES = ['new', 'contacted', 'qualified', 'proposal', 'won', 'lost'] as const;

export type LeadStatus = (typeof LEAD_STATUSES)[number];

/**
 * Statuses that mean the lead got past qualification.
 *
 * Lives here rather than in lib/analytics.ts because both sides need it now:
 * the write path stamps reachedQualified from it, and the read path falls back
 * to it for leads that predate that field. One definition, so the sticky flag
 * and the fallback can never disagree about what 'qualified' means.
 */
export const QUALIFIED_STATUSES: readonly LeadStatus[] = ['qualified', 'proposal', 'won'];

export function isQualifiedStatus(status: LeadStatus): boolean {
  return QUALIFIED_STATUSES.includes(status);
}

/**
 * One recorded move along the pipeline.
 *
 * `from` is kept as well as `to` so the timeline reads as a sentence without
 * having to reconstruct it from the previous entry — and so a gap in the
 * history is visible as one, rather than silently closing up.
 */
export type StatusChange = {
  from: LeadStatus;
  to: LeadStatus;
  at: Date;
};

/**
 * One document per form submission, in the `leads` collection.
 *
 * The attribution fields (landingPage, utm*, referrer) are the entire point:
 * formsubmit.co delivered a name and a message to an inbox and threw away
 * which page or campaign produced the lead.
 *
 * `id` is a Firestore document id — an opaque string, not a serial integer.
 * `createdAt`/`updatedAt` are stored as Firestore Timestamps and converted to
 * JS Date at the storage boundary, so every consumer sees a plain Date.
 */
export type Lead = {
  id: string;

  // Identity — the two fields every form requires.
  name: string;
  email: string;
  phone: string | null;

  // Qualification detail. Free text, not numeric: the forms collect bands
  // ("₹20L–₹2Cr"), not figures, and coercing them would lose information.
  brandName: string | null;
  website: string | null;
  monthlyRevenue: string | null;
  adSpend: string | null;
  message: string | null;

  // Attribution.
  sourceForm: string;
  landingPage: string | null;
  submittedFrom: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmTerm: string | null;
  referrer: string | null;

  // Pipeline state.
  status: LeadStatus;
  createdAt: Date;
  updatedAt: Date;

  /**
   * Every recorded transition, oldest first. Empty on leads that have not
   * moved, and also on leads that moved before this was recorded — the two are
   * told apart by whether status is still 'new'.
   */
  statusHistory: StatusChange[];

  /**
   * When the lead first moved off 'new'. Written once and never overwritten,
   * so a lead bounced back to 'new' and picked up again keeps its original
   * response time.
   *
   * null means one of two different things, and callers must not conflate
   * them: the lead has never been contacted (status is still 'new'), or it was
   * contacted before this field existed. lib/analytics.ts separates the two.
   */
  firstContactedAt: Date | null;

  /**
   * Sticky: set true on any transition into qualified, proposal or won, and
   * never unset. A lead that qualified and then lost still qualified, which
   * the current status alone cannot tell you.
   *
   * null means the lead predates the field, not that it failed to qualify.
   */
  reachedQualified: boolean | null;
};

/**
 * What a caller supplies on insert. The id is generated by Firestore and the
 * three stateful fields default at write time, mirroring the column defaults
 * the Postgres table carried.
 */
export type NewLead = Omit<
  Lead,
  // The three history fields are stamped by createLead, not supplied: a caller
  // must not be able to hand in a firstContactedAt.
  'id' | 'status' | 'createdAt' | 'updatedAt' | 'statusHistory' | 'firstContactedAt' | 'reachedQualified'
> & {
  status?: LeadStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Follow-up history, stored as a `notes` subcollection under its lead.
 * Append-only by design — notes are never edited or deleted, because "what did
 * we tell them in March" is a more useful question than "what is the current
 * summary".
 *
 * `leadId` is not a stored field: a note's parent is its position in the tree.
 * It is reconstructed on read so the shape the UI consumes is unchanged.
 */
export type LeadNote = {
  id: string;
  leadId: string;
  body: string;
  createdAt: Date;
};

export type NewLeadNote = {
  leadId: string;
  body: string;
  createdAt?: Date;
};
