/**
 * Lead shapes and pipeline vocabulary. Pure types and constants only.
 *
 * Kept separate from lib/firestore.ts on purpose: LEAD_STATUSES is a *value*,
 * so a client component importing it from the storage module would pull
 * firebase-admin — and node:crypto with it — into the browser bundle. Anything
 * that runs outside Node imports from here.
 */

/**
 * Pipeline stages, in order. Exported so the admin UI can render the funnel
 * without redeclaring the list and drifting out of sync with what is stored.
 */
export const LEAD_STATUSES = ['new', 'contacted', 'qualified', 'proposal', 'won', 'lost'] as const;

export type LeadStatus = (typeof LEAD_STATUSES)[number];

/**
 * One document per form submission, in the `leads` collection.
 *
 * The attribution fields (landingPage, utm*, referrer) are the entire point:
 * formsubmit.co delivered a name and a message to an inbox and threw away
 * which page or campaign produced the lead.
 *
 * `id` is a Firestore document id — an opaque string, not a serial integer.
 * `createdAt`/`updatedAt` are stored as Firestore Timestamps and converted to
 * JS Date at the storage boundary, so every consumer sees a plain Date.
 */
export type Lead = {
  id: string;

  // Identity — the two fields every form requires.
  name: string;
  email: string;
  phone: string | null;

  // Qualification detail. Free text, not numeric: the forms collect bands
  // ("₹20L–₹2Cr"), not figures, and coercing them would lose information.
  brandName: string | null;
  website: string | null;
  monthlyRevenue: string | null;
  adSpend: string | null;
  message: string | null;

  // Attribution.
  sourceForm: string;
  landingPage: string | null;
  submittedFrom: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmTerm: string | null;
  referrer: string | null;

  // Pipeline state.
  status: LeadStatus;
  createdAt: Date;
  updatedAt: Date;
};

/**
 * What a caller supplies on insert. The id is generated by Firestore and the
 * three stateful fields default at write time, mirroring the column defaults
 * the Postgres table carried.
 */
export type NewLead = Omit<Lead, 'id' | 'status' | 'createdAt' | 'updatedAt'> & {
  status?: LeadStatus;
  createdAt?: Date;
  updatedAt?: Date;
};

/**
 * Follow-up history, stored as a `notes` subcollection under its lead.
 * Append-only by design — notes are never edited or deleted, because "what did
 * we tell them in March" is a more useful question than "what is the current
 * summary".
 *
 * `leadId` is not a stored field: a note's parent is its position in the tree.
 * It is reconstructed on read so the shape the UI consumes is unchanged.
 */
export type LeadNote = {
  id: string;
  leadId: string;
  body: string;
  createdAt: Date;
};

export type NewLeadNote = {
  leadId: string;
  body: string;
  createdAt?: Date;
};
